export default function AISignal() {
  return (
    <div className="pt-32 pb-24 px-8 max-w-container-max mx-auto min-h-screen flex flex-col gap-8">
      {/* Page Header */}
      <header className="mb-4">
        <span className="font-label-caps text-label-caps text-secondary mb-2 block">Neural Network Feed</span>
        <h1 className="font-headline-md text-headline-md text-on-surface">Active Signal Intelligence</h1>
        <p className="text-on-surface-variant max-w-2xl mt-2">
          Real-time, institution-grade trading signals generated by our predictive models. Analyzed across 15+ timeframes and 50+ technical indicators.
        </p>
      </header>

      {/* Top Performance Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-card p-6 rounded-2xl flex items-center justify-between border-t border-secondary/30">
          <div>
            <div className="text-xs text-on-surface-variant uppercase tracking-wider font-bold mb-1">Win Rate (Weekly)</div>
            <div className="text-3xl font-bold text-on-surface">94.2%</div>
          </div>
          <div className="w-12 h-12 rounded-full bg-secondary/10 flex items-center justify-center">
            <span className="material-symbols-outlined text-secondary text-2xl">check_circle</span>
          </div>
        </div>
        <div className="glass-card p-6 rounded-2xl flex items-center justify-between border-t border-primary/30">
          <div>
            <div className="text-xs text-on-surface-variant uppercase tracking-wider font-bold mb-1">Total Pips Captured</div>
            <div className="text-3xl font-bold text-on-surface">+1,420</div>
          </div>
          <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
            <span className="material-symbols-outlined text-primary text-2xl">show_chart</span>
          </div>
        </div>
        <div className="glass-card p-6 rounded-2xl flex items-center justify-between border-t border-tertiary/30">
          <div>
            <div className="text-xs text-on-surface-variant uppercase tracking-wider font-bold mb-1">Active Signals</div>
            <div className="text-3xl font-bold text-on-surface">3</div>
          </div>
          <div className="w-12 h-12 rounded-full bg-tertiary/10 flex items-center justify-center">
            <span className="material-symbols-outlined text-tertiary text-2xl">sensors</span>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mt-4">
        
        {/* Left/Center Column: Live Signal Feed */}
        <div className="lg:col-span-2 flex flex-col gap-6">
          <div className="flex items-center justify-between border-b border-outline-variant/20 pb-4">
            <h2 className="text-xl font-bold text-on-surface">Live Signal Feed</h2>
            <div className="flex gap-2">
              <span className="px-3 py-1 text-xs font-bold bg-[#032EA1]/20 text-primary rounded-full border border-primary/30">All Pairs</span>
              <span className="px-3 py-1 text-xs font-bold text-on-surface-variant hover:text-on-surface cursor-pointer transition-colors">Forex</span>
              <span className="px-3 py-1 text-xs font-bold text-on-surface-variant hover:text-on-surface cursor-pointer transition-colors">Crypto</span>
            </div>
          </div>

          {/* Signal Card 1: Buy */}
          <div className="glass-card rounded-2xl p-6 border-l-4 border-l-secondary hover:bg-surface-variant/30 transition-colors cursor-pointer group">
            <div className="flex justify-between items-start mb-6">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-secondary/10 flex items-center justify-center text-secondary">
                  <span className="material-symbols-outlined text-3xl font-bold">arrow_upward</span>
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="text-2xl font-bold text-on-surface">GBP/JPY</h3>
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-secondary/20 text-secondary uppercase tracking-widest">Buy Limit</span>
                  </div>
                  <div className="text-sm text-on-surface-variant mt-1">Timeframe: 4H • Issued: 12 mins ago</div>
                </div>
              </div>
              <div className="text-right">
                <div className="text-3xl font-mono text-on-surface font-bold">190.450</div>
                <div className="text-xs text-secondary font-bold mt-1 tracking-wider">ENTRY ZONE</div>
              </div>
            </div>

            <div className="grid grid-cols-4 gap-4 bg-surface-container-lowest/50 p-4 rounded-xl border border-outline-variant/10">
              <div>
                <div className="text-[10px] text-error font-bold uppercase mb-1">Stop Loss</div>
                <div className="font-mono text-sm">189.800</div>
                <div className="text-[10px] text-on-surface-variant mt-1">-65 Pips</div>
              </div>
              <div className="border-l border-outline-variant/20 pl-4">
                <div className="text-[10px] text-on-surface-variant font-bold uppercase mb-1">Take Profit 1</div>
                <div className="font-mono text-sm">191.100</div>
                <div className="text-[10px] text-secondary mt-1">+65 Pips</div>
              </div>
              <div className="border-l border-outline-variant/20 pl-4">
                <div className="text-[10px] text-on-surface-variant font-bold uppercase mb-1">Take Profit 2</div>
                <div className="font-mono text-sm">191.750</div>
                <div className="text-[10px] text-secondary mt-1">+130 Pips</div>
              </div>
              <div className="border-l border-outline-variant/20 pl-4">
                <div className="text-[10px] text-secondary font-bold uppercase mb-1">Take Profit 3</div>
                <div className="font-mono text-sm text-secondary font-bold">192.400</div>
                <div className="text-[10px] text-secondary mt-1">+195 Pips (1:3 RR)</div>
              </div>
            </div>

            <div className="mt-6 flex justify-between items-center">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-secondary animate-pulse"></div>
                <span className="text-xs font-bold text-on-surface">Status: <span className="text-secondary">Waiting for Entry</span></span>
              </div>
              <button className="bg-[#032EA1] text-white px-6 py-2 rounded-full text-sm font-bold opacity-0 group-hover:opacity-100 transition-opacity">Auto Execute</button>
            </div>
          </div>

          {/* Signal Card 2: Sell */}
          <div className="glass-card rounded-2xl p-6 border-l-4 border-l-error hover:bg-surface-variant/30 transition-colors cursor-pointer group">
            <div className="flex justify-between items-start mb-6">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-error/10 flex items-center justify-center text-error">
                  <span className="material-symbols-outlined text-3xl font-bold">arrow_downward</span>
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="text-2xl font-bold text-on-surface">EUR/USD</h3>
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-error/20 text-error uppercase tracking-widest">Sell Market</span>
                  </div>
                  <div className="text-sm text-on-surface-variant mt-1">Timeframe: 1H • Issued: 45 mins ago</div>
                </div>
              </div>
              <div className="text-right">
                <div className="text-3xl font-mono text-on-surface font-bold">1.09420</div>
                <div className="text-xs text-error font-bold mt-1 tracking-wider">ENTRY ZONE</div>
              </div>
            </div>

            <div className="grid grid-cols-4 gap-4 bg-surface-container-lowest/50 p-4 rounded-xl border border-outline-variant/10">
              <div>
                <div className="text-[10px] text-error font-bold uppercase mb-1">Stop Loss</div>
                <div className="font-mono text-sm">1.09720</div>
                <div className="text-[10px] text-on-surface-variant mt-1">-30 Pips</div>
              </div>
              <div className="border-l border-outline-variant/20 pl-4">
                <div className="text-[10px] text-on-surface-variant font-bold uppercase mb-1">Take Profit 1</div>
                <div className="font-mono text-sm line-through opacity-50">1.09120</div>
                <div className="text-[10px] text-secondary mt-1">HIT ✓</div>
              </div>
              <div className="border-l border-outline-variant/20 pl-4">
                <div className="text-[10px] text-on-surface-variant font-bold uppercase mb-1">Take Profit 2</div>
                <div className="font-mono text-sm text-secondary font-bold">1.08820</div>
                <div className="text-[10px] text-secondary mt-1">+60 Pips</div>
              </div>
              <div className="border-l border-outline-variant/20 pl-4">
                <div className="text-[10px] text-secondary font-bold uppercase mb-1">Take Profit 3</div>
                <div className="font-mono text-sm">1.08520</div>
                <div className="text-[10px] text-secondary mt-1">+90 Pips (1:3 RR)</div>
              </div>
            </div>

            <div className="mt-6 flex justify-between items-center">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-primary animate-pulse"></div>
                <span className="text-xs font-bold text-on-surface">Status: <span className="text-primary">Active (Risk Free)</span></span>
              </div>
              <button className="bg-[#032EA1] text-white px-6 py-2 rounded-full text-sm font-bold opacity-0 group-hover:opacity-100 transition-opacity">Manage Trade</button>
            </div>
          </div>
        </div>

        {/* Right Column: AI Deep Dive Sidebar */}
        <div className="flex flex-col gap-6">
          <div className="glass-card rounded-2xl p-6 border border-primary/20 bg-gradient-to-b from-primary/5 to-transparent sticky top-24">
            <div className="flex items-center gap-2 mb-6 border-b border-outline-variant/20 pb-4">
              <span className="material-symbols-outlined text-primary">psychology</span>
              <h3 className="text-lg font-bold text-on-surface">AI Deep Dive: GBP/JPY</h3>
            </div>
            
            <div className="mb-6">
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm text-on-surface-variant font-bold">AI Confidence Score</span>
                <span className="text-lg font-bold text-secondary">94%</span>
              </div>
              <div className="w-full h-2 bg-surface-container rounded-full overflow-hidden">
                <div className="h-full bg-gradient-to-r from-secondary to-primary w-[94%]"></div>
              </div>
            </div>

            <div className="space-y-4 mb-6">
              <div className="bg-surface-container-lowest p-3 rounded-xl border border-outline-variant/10">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-xs font-bold text-on-surface">Order Block (4H)</span>
                  <span className="material-symbols-outlined text-secondary text-[16px]">check_circle</span>
                </div>
                <div className="text-[11px] text-on-surface-variant">Price tapped into bullish institutional order block at 189.900.</div>
              </div>
              <div className="bg-surface-container-lowest p-3 rounded-xl border border-outline-variant/10">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-xs font-bold text-on-surface">RSI Divergence</span>
                  <span className="material-symbols-outlined text-secondary text-[16px]">check_circle</span>
                </div>
                <div className="text-[11px] text-on-surface-variant">Hidden bullish divergence forming on the 1H timeframe.</div>
              </div>
              <div className="bg-surface-container-lowest p-3 rounded-xl border border-outline-variant/10">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-xs font-bold text-on-surface">Volume Profile</span>
                  <span className="material-symbols-outlined text-error text-[16px]">warning</span>
                </div>
                <div className="text-[11px] text-on-surface-variant">Slight resistance expected at 191.100 HVN node.</div>
              </div>
            </div>

            <div className="mt-auto">
              <div className="text-xs font-bold text-primary uppercase mb-2 flex items-center gap-1">
                <span className="material-symbols-outlined text-[14px]">smart_toy</span> AI Commentary
              </div>
              <p className="text-sm text-on-surface-variant leading-relaxed italic border-l-2 border-primary/50 pl-3">
                "The algorithm detected a significant liquidity sweep below the Asian session lows. Coupling this with the BOJ interest rate hold, yen weakness is projected to accelerate against the pound. The entry is optimized for a 1:3 risk-to-reward ratio."
              </p>
            </div>
            
            <button className="w-full mt-6 border border-[#032EA1] text-[#032EA1] hover:bg-[#032EA1] hover:text-white transition-colors py-2 rounded-full text-sm font-bold">
              View Full Report
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
